from typing import TypedDict, List, Optional, Dict, Any
import pandas as pd

class AgentState(TypedDict):
    """
    Defines the state that flows through the agentic graph.
    """
    # Original query from the user
    user_query: str 
    
    # The multi-step plan generated by the Planner
    plan: List[str] 
    
    # The full DataFrame loaded from CSV
    full_data: pd.DataFrame 
    
    # Summarized data or specific data cuts for analysis
    data_summary: Optional[str] 
    
    # List of hypotheses generated by the Insight Agent
    # Format: {"hypothesis": "...", "confidence": 0.0, "evidence": "..."}
    hypotheses: List[Dict[str, Any]]
    
    # Validated insights that passed the Evaluator's checks
    validated_insights: List[Dict[str, Any]]
    
    # IDs or names of low-CTR campaigns to focus on
    low_ctr_campaigns: List[str]
    
    # Generated creative recommendations
    # Format: {"campaign_name": "...", "new_headlines": [], "new_messages": []}
    creative_recommendations: List[Dict[str, Any]]
    
    # For reflection and retry logic
    log: List[str]